-- CATEGORIA
INSERT INTO CATEGORIA (CODCAT, NOME)
VALUES (CATEGORIA_SEQ.NEXTVAL, 'Eletrônicos');

INSERT INTO CATEGORIA (CODCAT, NOME)
VALUES (CATEGORIA_SEQ.NEXTVAL, 'Moda');

INSERT INTO CATEGORIA (CODCAT, NOME)
VALUES (CATEGORIA_SEQ.NEXTVAL, 'Alimentos');

INSERT INTO CATEGORIA (CODCAT, NOME)
VALUES (CATEGORIA_SEQ.NEXTVAL, 'Móveis');

INSERT INTO CATEGORIA (CODCAT, NOME)
VALUES (CATEGORIA_SEQ.NEXTVAL, 'Beleza');

INSERT INTO CATEGORIA (CODCAT, NOME)
VALUES (CATEGORIA_SEQ.NEXTVAL, 'Esportes');
