-- FORNECIMENTO
-- Fornecedor 400
INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (1, 400);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (2, 400);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (3, 400);

-- Fornecedor 500
INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (4, 500);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (5, 500);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (6, 500);

-- Fornecedor 300
INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (7, 300);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (8, 300);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (9, 300);

-- Fornecedor 100
INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (10, 100);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (11, 100);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (12, 100);

-- Fornecedor 200
INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (13, 200);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (14, 200);

INSERT INTO FORNECIMENTO (CODIGO_PRODUTO, CODIGO_FORNECEDOR)
VALUES (15, 200);