-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 08:42:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancodedadosusandomodelo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancodedadosusandomodelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancodedadosusandomodelo` DEFAULT CHARACTER SET utf8 ;
USE `bancodedadosusandomodelo` ;

-- -----------------------------------------------------
-- Table `bancodedadosusandomodelo`.`tipocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedadosusandomodelo`.`tipocliente` (
  `i_tipocliente_tipocliente` TINYINT NOT NULL,
  `s_dsctipocliente_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`i_tipocliente_tipocliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodedadosusandomodelo`.`cleinte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedadosusandomodelo`.`cleinte` (
  `i_cliente_cliente` INT NOT NULL,
  `s_nome_cliente` VARCHAR(50) NOT NULL,
  `s_cpf_cliente` VARCHAR(11) NOT NULL,
  `d_nascimento_cliente` DATETIME NULL,
  `i_tipo_cliente` TINYINT NOT NULL,
  PRIMARY KEY (`i_cliente_cliente`),
  INDEX `fk_cleinte_tipocliente_idx` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cleinte_tipocliente`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `bancodedadosusandomodelo`.`tipocliente` (`i_tipocliente_tipocliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
