SELECT MAX(NF.VALOR_TOTAL) AS MAIOR_VALOR_COMPRA
FROM ORDEM_DE_COMPRA OC
JOIN CLIENTE C ON OC.CODIGO_CLIENTE = C.CODCLI
JOIN NOTA_FISCAL NF ON OC.CODORDEM = NF.COD_ORDEM_COMPRA
WHERE EXTRACT(YEAR FROM C.DATA_NASCIMENTO) BETWEEN 1990 AND 1999
  AND C.END_CIDADE = 'Campina Grande';